name: 'Run Codeship'
description: 'Run codeship'
inputs:
  user:
    description: 'Codeship User'
    required: true
  password: 
    description: 'Codeship Password'
    required: true
  organization-id:
    description: 'Organization ID'
    required: true
  project-id:
    description: 'Project ID'
    required: true
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
